[{"file":"pq-yP7mb8UE", "provider":"youtube", "title":"I Will Possess Your Heart (Album Version video)"},
{"file":"cYF0LtfUvJs", "provider":"youtube", "title":"Jack White - &quot;Lazaretto&quot; (Audio)"},
{"file":"tcI914sM2wQ", "provider":"youtube", "title":"Deftones - Lhabia"},
{"file":"XOzs1FehYOA", "provider":"youtube", "title":"Deftones - My Own Summer "},
{"file":"I3BFI8lqhzM", "provider":"youtube", "title":"Hjaltalín - I Feel You (Official Video)"},
{"file":"woAcXSMyCEw", "provider":"youtube", "title":"Deftones - You've Seen The Butcher "},
{"file":"WUP9E5jJrr4", "provider":"youtube", "title":"The Dillinger Escape Plan &quot;Happiness Is A Smile&quot;"},
{"file":"C5lRSAnf--0", "provider":"youtube", "title":"The xx - Chained (Liar Remix)"},
{"file":"MPH89HIBLiw", "provider":"youtube", "title":"Alt-J - &quot;Tessellate&quot; (Official Video)"},
{"file":"oqn9gRZGIak", "provider":"youtube", "title":"Grouplove - Ways To Go (Thom Alt-J Remix)"},
{"file":"I7hEdK47zLM", "provider":"youtube", "title":"Alt-J - Dancing in the Moonlight cover"},
{"file":"75-GbbfZ5fg", "provider":"youtube", "title":"The Kooks - Forgive &amp; Forget"},
{"file":"rVeMiVU77wo", "provider":"youtube", "title":"alt-J  Breezeblocks"},
{"file":"5jwoOODS0TQ", "provider":"youtube", "title":"Gold Panda - Marriage (Star Slinger Remix) OFFICIAL / HD"},
{"file":"TgwrxcO48N8", "provider":"youtube", "title":"Nine Inch Nails - Came Back Haunted "},
{"file":"2hG1q2szezE", "provider":"youtube", "title":"A Dog Called Ego - Tell Me That I´m Not Awake"},
{"file":"WbrjRKB586s", "provider":"youtube", "title":"When The Levee Breaks Led Zeppelin +Lyrics"},
{"file":"YHT-yNNzadc", "provider":"youtube", "title":"Flume &amp; Chet Faker - What About Us"},
{"file":"CjwwmFrsX_E", "provider":"youtube", "title":"Chvrches cover Arctic Monkeys' 'Do I Wanna Know?' for Like A Version"},
{"file":"YtfB8MqP1jU", "provider":"youtube", "title":"Warpaint - Love is to Die (Yours Truly Session)"},
{"file":"dGcoty6R7gA", "provider":"youtube", "title":"Timpuri Noi - Perfect (1992)"},
{"file":"7E0fVfectDo", "provider":"youtube", "title":"Arcade Fire - Reflektor"},
{"file":"Ro6Z1__BVnE", "provider":"youtube", "title":"Circadian Eyes - Who We Were (Official Music Video)"},
{"file":"3iXMhphebGI", "provider":"youtube", "title":"Tool - H."},
{"file":"yF-GvT8Clnk", "provider":"youtube", "title":"Portishead - glory box"},
{"file":"-JtXZsUlI68", "provider":"youtube", "title":"Moloko - Sing It Back (Herbert's Tasteful Dub)"},
{"file":"6UQ6QZIGKro", "provider":"youtube", "title":"Seasick Steve - Thunderbird"},
{"file":"XE2051n3O-I", "provider":"youtube", "title":"Brody Dalle - Don't Mess With Me"},
{"file":"MCJ7_NPtNEo", "provider":"youtube", "title":"Wild Beasts - Mecca"},
{"file":"qSf4sdxdMaw", "provider":"youtube", "title":"Vita de Vie - Iamma (acustic)"},
{"file":"3j4I0PqNzKE", "provider":"youtube", "title":"NONONO - Pumpin Blood "},
{"file":"iZZUY32iCzU", "provider":"youtube", "title":"The Black Keys - Fever [Official Audio]"},
{"file":"LiEMLOk9BwU", "provider":"youtube", "title":"George Ezra - Budapest"},
{"file":"uhfXl1OefI8", "provider":"youtube", "title":"Catfish and the Bottlemen - Homesick (Official Video) - EP Version"},
{"file":"ST6nEvIEY4s", "provider":"youtube", "title":"Kasabian - Eez-Eh"},
{"file":"bl2klvFt0DQ", "provider":"youtube", "title":"Chet Faker - Cigarettes &amp; Chocolate (Schism Remix)"},
{"file":"AZ5uaoc6Iss", "provider":"youtube", "title":"Sorry For It All | Dead Sara | Official Video"},
{"file":"ZEbBIswSsEA", "provider":"youtube", "title":"Band of Skulls - Death By Diamonds And Pearls"},
{"file":"MT4OxLLI4m4", "provider":"youtube", "title":"Wheelharp"},
{"file":"k_EhHcZzUoE", "provider":"youtube", "title":"Alt-J - Hunger of the Pine"},
{"file":"Ph5psMQoirU", "provider":"youtube", "title":"Crazy P - Heartbreaker"},
{"file":"WRsS4JS-w-E", "provider":"youtube", "title":"Vita de Vie - Liber (acustic)"},
{"file":"rId6PKlDXeU", "provider":"youtube", "title":"Mumford &amp; Sons - Hopeless Wanderer."},
{"file":"chFmFpTc21s", "provider":"youtube", "title":"múm - Finally We Are No One [ Full album ]"},
{"file":"14dPCN5B79M", "provider":"youtube", "title":"Valerinne - Hysterema (Official Video)"},
{"file":"_XaWV7oNVis", "provider":"youtube", "title":"Sigur Rós  - I Gaer"},
{"file":"6PDDORfQZZ8", "provider":"youtube", "title":"Karnivool cover London Grammar 'Hey Now' for Like A Version"},
{"file":"19_n0Fxn8S4", "provider":"youtube", "title":"WARPAINT 'Beetles'"},
{"file":"LZgNBSkaTQQ", "provider":"youtube", "title":"Warpaint - Biggy"},
{"file":"wAB4kz4Itiw", "provider":"youtube", "title":"Warpaint - Son"},
{"file":"sWVOGaakRE8", "provider":"youtube", "title":"Warpaint - Warpaint"},
{"file":"bkysjcs5vFU", "provider":"youtube", "title":"dio - holy diver"},
{"file":"bH2I9fJ0ALk", "provider":"youtube", "title":"Thom Yorke With PJ Harvey - This Mess Where In"},
{"file":"bWkYu-hYTZs", "provider":"youtube", "title":"Kings Of Leon - Cold Desert"},
{"file":"cirNGjzPY6o", "provider":"youtube", "title":"Our Ceasing Voice &amp; Matthew Ryan - Until Your Chest Explodes (official)"},
{"file":"gEIVzWCRSg8", "provider":"youtube", "title":"Black Violin - &quot;A Flat&quot; (Music Video) (2012)"},
{"file":"RfKYXz7mZhI", "provider":"youtube", "title":"Foxtails Brigade - &quot;Don't Look Down&quot; - Farmhouse Sessions 1 of 4"},
{"file":"IaZUysCPFFY", "provider":"youtube", "title":"Alexandrina - Avionul de Aur @GuerriLIVE Radio Session"},
{"file":"4gO7uemm6Yo", "provider":"youtube", "title":"Suicide is Painless "},
{"file":"IbzxhZT6akk", "provider":"youtube", "title":"Fantasia on a Theme by Thomas Tallis (Eugene Ormandy &amp; Philadelphia Orchestra)"},
{"file":"SLiR_MT6toQ", "provider":"youtube", "title":"Crippled Black Phoenix - The Heart Of Every Country (album version)"},
{"file":"ggHlujmXGLk", "provider":"youtube", "title":"SOHN - The Wheel (Phattcut Remix)"},
{"file":"N2RNe2jwHE0", "provider":"youtube", "title":"Jethro Tull - Bourée"},
{"file":"xir-5oAWxXE", "provider":"youtube", "title":"Itzhak Perlman plays Sarasate / Zigeunerweisen"},
{"file":"exMaFoEtx5Q", "provider":"youtube", "title":"Kaleidonescu- Ciudat (L.A. remake)"},
{"file":"6ejrM1wR6Ow", "provider":"youtube", "title":"Strike Anywhere &quot;I'm Your Opposite Number&quot; (Official Music Video - HD)"},
{"file":"V_E5ae9ZTwk", "provider":"youtube", "title":"Karnivool &quot;We Are&quot; - Official Video"},
{"file":"0Ok0expLH1o", "provider":"youtube", "title":"Muse United States of Eurasia"},
{"file":"ItP8fvrqREw", "provider":"youtube", "title":"Dusty Old Records - Communication Breakdown"},
{"file":"EynaXGRJIcc", "provider":"youtube", "title":"byron - Zeitgeist"},
{"file":"MQvZ4N1RfS8", "provider":"youtube", "title":"Arcade Fire - Rebellion "},
{"file":"AZ3hL_51tqs", "provider":"youtube", "title":"Fluturi Pe Asfalt - Niciodata degeaba"},
{"file":"PLFVGwGQcB0", "provider":"youtube", "title":"Erik Satie - Gnossienne No.1"},
{"file":"O_kFevKifug", "provider":"youtube", "title":"urma - buy me with a coffee"},
{"file":"xwDvhVOWUvQ", "provider":"youtube", "title":"Lorn &amp; Dolor - Drugs - 1. My Keys // Black Ice"},
{"file":"d3B30NT_ZWs", "provider":"youtube", "title":"NAVA MAMA - trei clopote (live in Studioul de Baza)"},
{"file":"kJpVJpI5z64", "provider":"youtube", "title":"Rocket Juice &amp; The Moon - Poison (feat. Damon Albarn)"},
{"file":"1_O_T6Aq85E", "provider":"youtube", "title":"Arctic Monkeys - Snap Out Of It (Official Audio)"},
{"file":"zbp60IX_jFQ", "provider":"youtube", "title":"Death - Symbolic"},
{"file":"_ZP9IxR7njI", "provider":"youtube", "title":"18 Romani Holiday (Antonius Remix) - Hans Zimmer - Sherlock Holmes A Game of Shadows Score"},
{"file":"NznljGV66HY", "provider":"youtube", "title":"Pink Floyd Final Cut  - Two Suns In The Sunset"},
{"file":"zvCBSSwgtg4", "provider":"youtube", "title":"The Lumineers - Ho Hey "},
{"file":"ZpUYjpKg9KY", "provider":"youtube", "title":"Limp Bizkit - Break Stuff"},
{"file":"B32yjbCSVpU", "provider":"youtube", "title":"Ugly Kid Joe - Cats In The Cradle"},
{"file":"ZKsf6OQ5cPQ", "provider":"youtube", "title":"Coin Operated Goi by Voltaire (OFFICIAL)"},
{"file":"Z6k35s8YZlU", "provider":"youtube", "title":"ABRAHAM — Start with a Heartbeat (music video)"},
{"file":"w3Q2L1Tt1Hk", "provider":"youtube", "title":"Jethro Tull The Whistler"},
{"file":"x4vMvJcP4TA", "provider":"youtube", "title":"Mastodon - Dry Bone Valley [Official Music Video]"},
{"file":"BrCQFnjr-xk", "provider":"youtube", "title":"Red Hot Chili Peppers - Coffee Shop "},
{"file":"YjIg5lrbEwU", "provider":"youtube", "title":"TIAMAT - Cain (OFFICIAL VIDEO)"},
{"file":"mzycLGudWTw", "provider":"youtube", "title":"KORPIKLAANI - Tequila"},
{"file":"WVHlRCpwU8c", "provider":"youtube", "title":"Karma to Burn - Waiting On the Western World"},
{"file":"K626gMvu2ds", "provider":"youtube", "title":"Rage Against the Machine - Renegades of Funk"},
{"file":"U-tUbTU0jIA", "provider":"youtube", "title":"BSG Orchestra - Apocalypse (Live)"},
{"file":"tDl3bdE3YQA", "provider":"youtube", "title":"Edie Brickell &amp; New Bohemians - What I Am"},
{"file":"fte2YrMta7g", "provider":"youtube", "title":"Mastodon - Stargasm"},
{"file":"Uuq6HgKgEFQ", "provider":"youtube", "title":"D-12 - Purple Hills"},
{"file":"Twv7z0_STCM", "provider":"youtube", "title":"Dream a Little Dream - Eddie Vedder"},
{"file":"u_tORtmKIjE", "provider":"youtube", "title":"The Bard`s Song "},
{"file":"ClRsUOY7ij8", "provider":"youtube", "title":"Queen - Don't Lose Your Head"},
{"file":"SBjQ9tuuTJQ", "provider":"youtube", "title":"Foo Fighters - The Pretender"},
{"file":"SSbBvKaM6sk", "provider":"youtube", "title":"Blur - Song 2"},
{"file":"qkHSvwKgJQA", "provider":"youtube", "title":"Cult Of Luna - &quot;I,The Weapon&quot;"},
{"file":"Qu_rItLPTXc", "provider":"youtube", "title":"Peter Paul &amp; Mary - Puff the Magic Dragon"},
{"file":"7WwaPv1rZiQ", "provider":"youtube", "title":"Lisa Hannigan - I Don't Know"},
{"file":"IrTB-iiecqk", "provider":"youtube", "title":"Radiohead - Street Spirit (Fade Out)"},
{"file":"NOG3eus4ZSo", "provider":"youtube", "title":"The Smashing Pumpkins - Tonight, Tonight"},
{"file":"nMJUbZrNnA8", "provider":"youtube", "title":"Mumford &amp; Sons - Lover Of The Light"},
{"file":"N-ulb7QwFeQ", "provider":"youtube", "title":"Slow Six - The Night You Left New York"},
{"file":"LJ7qXHjxj_0", "provider":"youtube", "title":"Michael Jackson  -  Give in to Me - OFFICIAL VIDEO"},
{"file":"m6BQKFs3-VM", "provider":"youtube", "title":"Once Upon A Time In The West - Man With A Harmonica"},
{"file":"LoQYw49saqc", "provider":"youtube", "title":"Gorillaz - Clint Eastwood"},
{"file":"LAQDcnwwspQ", "provider":"youtube", "title":"Grails - Satori"},
{"file":"lTGUm_LEVB8", "provider":"youtube", "title":"Rotting Christ - Cine Iubeste Si Lasa"},
{"file":"LV1Ymtz1a9w", "provider":"youtube", "title":"Hugh Laurie - You Don't Know My Mind 2011 -  (NEW) - Yahoo! Music"},
{"file":"lB6a-iD6ZOY", "provider":"youtube", "title":"Sting - Fragile"},
{"file":"0JSXCfGWjqA", "provider":"youtube", "title":"Liquido - Narcotic"},
{"file":"kTo1ngmwDoc", "provider":"youtube", "title":"Hot Potato Syncopators- Ukulele Hooley 2012"},
{"file":"kH4Hr_ZxyZs", "provider":"youtube", "title":"Radiohead - Sail To the Moon (Acoustic Cover) [HD]"},
{"file":"jW7VhkNqjnc", "provider":"youtube", "title":"Green Day - Kill The DJ "},
{"file":"XlT8Ojbi5Y4", "provider":"youtube", "title":"Opeth - To Rid the Disease"},
{"file":"jZhQOvvV45w", "provider":"youtube", "title":"One Republic Good life with Lyrics"},
{"file":"Km0SXsjTFzI", "provider":"youtube", "title":"LONG DISTANCE CALLING - Into The Black Wide Open (OFFICIAL VIDEO)"},
{"file":"GvdWibyHvbk", "provider":"youtube", "title":"Treefingers [LIVE DEBUT] Radiohead @ Arènes de Nimes 10-07-12"},
{"file":"gy5Ve3338-E", "provider":"youtube", "title":"Ravel - Bolero. Sergiu Celibidache 1971"},
{"file":"2CTPLUcQAjk", "provider":"youtube", "title":"Queen - Bicycle Race"},
{"file":"hSsjxbRxgqY", "provider":"youtube", "title":"A Saucerful of Secrets - Live at Pompeii - Pink Floyd"},
{"file":"J5OeJEFjUdU", "provider":"youtube", "title":"Days of Confusion - &quot;Meta&quot; - BlankTV World Premiere!"},
{"file":"GYydWVIgYlA", "provider":"youtube", "title":"Grace For Drowning + Sectarian - Steven Wilson"},
{"file":"JazOLeHqp-Y", "provider":"youtube", "title":"Sleep Party People - A Dark God Heart"},
{"file":"I2oRY7W_WUs", "provider":"youtube", "title":"Muse: Man with the Harmonica &amp; Knights of Cydonia Teignmouth 2009"},
{"file":"HEu5P1YmUqA", "provider":"youtube", "title":"Apocalyptica Feat  Nina Hagen   Seemann 720p"},
{"file":"g5NfwZRBrKE", "provider":"youtube", "title":"Grails - Deep Politics"},
{"file":"GLF46JKkCNg", "provider":"youtube", "title":"Sachal Studios' Take Five Official Video"},
{"file":"NOPRrXXWORk", "provider":"youtube", "title":"David Bowie - Slow Burn"},
{"file":"FMnTQEvHb1A", "provider":"youtube", "title":"Death - Zero Tolerance (Live in Eindhoven 1998) (High Quality)"},
{"file":"GnHQUf9X7Oo", "provider":"youtube", "title":"Incantatie/ Chant - DAC'ART (Video)"},
{"file":"F3aYamXs1Fg", "provider":"youtube", "title":"Alternativ Quartet -01- Hopus"},
{"file":"DJo0VQ275m8", "provider":"youtube", "title":"Valerinne - Medusa (live Control Club / 27.02.2013)"},
{"file":"Eqcf8e8fN_A", "provider":"youtube", "title":"Spitalul de urgenta - Prietenii "},
{"file":"C55VW_o1V3U", "provider":"youtube", "title":"Antimatter - Wide Awake In The Concrete Asylum"},
{"file":"eYIQy5ze2eM", "provider":"youtube", "title":"&quot;The Mexican&quot; by Babe Ruth"},
{"file":"GUeHaR24f8Y", "provider":"youtube", "title":"Funkadelic - Funkadelic - 05 - Good Old Music"},
{"file":"cfOa1a8hYP8", "provider":"youtube", "title":"Radiohead - Lotus Flower"},
{"file":"dR7xBj0bDD8", "provider":"youtube", "title":"Kreator-Violent Revolution "},
{"file":"ef-4Bv5Ng0w", "provider":"youtube", "title":"Frédéric Chopin - Prelude in E-Minor "},
{"file":"oMqPeytXNW4", "provider":"youtube", "title":"&quot;Society&quot; (Live) - Eddie Vedder ft. Liam Finn - Water on the Road"},
{"file":"dvBPCm25z4I", "provider":"youtube", "title":"Radiohead - A Wolf at the Door"},
{"file":"CgVqX0a49HM", "provider":"youtube", "title":"(Michael Jackson) Billie Jean - Sungha Jung"},
{"file":"GV3wYPXFiBY", "provider":"youtube", "title":"Careful with That Axe, Eugene - Pink Floyd - Live At Pompeii - 1972 - HD"},
{"file":"aE_3n9tU1_Q", "provider":"youtube", "title":"Queens Of The Stone Age - Mosquito Song"},
{"file":"3cJxIi4Dhjw", "provider":"youtube", "title":"lake of tears - so fell autumn rain"},
{"file":"bC5HQJjDEuI", "provider":"youtube", "title":"Tides From Nebula - Hollow Lights"},
{"file":"BaWxsWl7XGo", "provider":"youtube", "title":"Introspector ft Nathan Flutebox Lee live (Engine-EarZ Experiment)"},
{"file":"VbpMpRq6DV4", "provider":"youtube", "title":"David Bowie - Wild Is The Wind"},
{"file":"9IPzwiKk0BE", "provider":"youtube", "title":"The Revels - Comanche PULP FICTION soundtrack"},
{"file":"IxNYP-OaPhE", "provider":"youtube", "title":"Baroness - March To The Sea"},
{"file":"9tpMhl1W9-o", "provider":"youtube", "title":"Jazz Compilation 2012 Part 2"},
{"file":"9wV9_je85DE", "provider":"youtube", "title":"Muse - Stockholm Syndrome [Live From Wembley Stadium]"},
{"file":"7Bj8_H7E_N0", "provider":"youtube", "title":"Byron - No man's land"},
{"file":"2pi5jdkO94A", "provider":"youtube", "title":"José González - Cycling Trivialities"},
{"file":"4N6jgvjLbhk", "provider":"youtube", "title":"Alternativ Quartet -08- Toshiga ii"},
{"file":"5LXKd3nPqqg", "provider":"youtube", "title":"Buzzy, Tonyca, Rapsodic, Microscop, Ctin, Rumano, So What  - Tulcea (Mana sus!) Hip-Hop Romania 2011"},
{"file":"0S43IwBF0uM", "provider":"youtube", "title":"The Chemical Brothers - Star Guitar"},
{"file":"46aqrQXSZdA", "provider":"youtube", "title":"Baroness - Stretchmarker [Acoustic / December 2012]"},
{"file":"zE88dkwB5VI", "provider":"youtube", "title":"Placebo - B3 "},
{"file":"0RuWOX_Gw8c", "provider":"youtube", "title":"Phoenix-Filip si cerbul"},
{"file":"tXyuH1yx5g8", "provider":"youtube", "title":"Tom Waits &quot;Warm beer and cold women&quot; live from Nighthawks at the diner"},
{"file":"NS3m0-4bM9s", "provider":"youtube", "title":"The Doors - The End (Apocalypse Now Version)"},
{"file":"-qYqi-EMErU", "provider":"youtube", "title":"Metallica - Orion (Studio Version)"},
{"file":"0s7E2uIn3tM", "provider":"youtube", "title":"Subcarpati - Frunzulita iarba deasa (cu Madalina Paval si AFO)"},
{"file":"fngjZUHf2QE", "provider":"youtube", "title":"Damon Albarn - Sunset Coming On"},
{"file":"khxwXX9G7Uc", "provider":"youtube", "title":"Pasarea Colibri Vis de primavara"},
{"file":"10xwyADw4gI", "provider":"youtube", "title":"Karnivool - We Are (live on triple j)"},
{"file":"YzR8BCmV9Ew", "provider":"youtube", "title":"Here With Me - Susie Suh x Robot Koch"},
{"file":"9c2ZJPKz5u8", "provider":"youtube", "title":"Bear McCreary - Kara Remembers (piano cylon song full version) Battlestar Galactica Season 4"},
{"file":"oO5fDztl_fg", "provider":"youtube", "title":"Luna Amara - Deadends - acustic - Live la Teatru Fix iasi"},
{"file":"sRbnAxrS3EM", "provider":"youtube", "title":"Jack White - &quot;High Ball Stepper&quot; (Lazaretto Album Track)"},
{"file":"_zsnGq4rvEM", "provider":"youtube", "title":"PINK FLOYD - WHAT DO YOU WANT FROM ME [ HQ ]"},
{"file":"13EifDb4GYs", "provider":"youtube", "title":"Moby - Porcelain"},
{"file":"bC8EmPA6H6g", "provider":"youtube", "title":"Slash ft.Myles Kennedy &amp; The Conspirators - Anastasia | Live in Sydney | Moshcam"},
{"file":"xsHF-8xUFPA", "provider":"youtube", "title":"Jefferson Airplane - In the morning"},
{"file":"ycYewhiaVBk", "provider":"youtube", "title":"Steven Wilson - Drive Home"},
{"file":"JsxavPANO8s", "provider":"youtube", "title":"Its the end of the world by R.E.M lyrics"},
{"file":"7vBRiFfXIiA", "provider":"youtube", "title":"Alexandra Usurelu si Mircea Vintila - Ceva se intampla cu noi (videoclip oficial)"},
{"file":"PoPL7BExSQU", "provider":"youtube", "title":"Blue in Green by. Miles Davis"},
{"file":"peRS3KGNxoY", "provider":"youtube", "title":"Flume - Insane feat. Moon Holiday"},
{"file":"q7FVgfGtzsA", "provider":"youtube", "title":"The Decemberists: California One / Youth and Beauty Brigade"},
{"file":"cFmjO4mY1zs", "provider":"youtube", "title":"COMA - CHIP [official video 2014]"},
{"file":"PBUyL4NUDks", "provider":"youtube", "title":"Lights Out - Nepal (Official Music Video)"},
{"file":"xB5ceAruYrI", "provider":"youtube", "title":"The Lion King - Hakuna Matata "},
{"file":"euxJvqnzKgk", "provider":"youtube", "title":"The Prodigy - Smack My Bitch Up (Noisia Remix)"},
{"file":"m4gQTYGHfRg", "provider":"youtube", "title":"Xavier Rudd - Come Let Go "},
{"file":"eMwn_hnoS5Y", "provider":"youtube", "title":"Peter Gabriel - Solsbury Hill"},
{"file":"vPzDTfIb0DU", "provider":"youtube", "title":"Faith No More - Easy (Official Music Video)"},
{"file":"HFHKUcILp9s", "provider":"youtube", "title":"Animaniacs - Saturday Morning Slow Jams"},
{"file":"5dbeMmABsMA", "provider":"youtube", "title":"OCS - Cea Mai Frumoasa Zi"},
{"file":"gj4ST5Dsmdc", "provider":"youtube", "title":"2CELLOS - Bach Double Violin Concerto in D minor - 2nd mov [LIVE VIDEO]"},
{"file":"l8JTLlmbOVk", "provider":"youtube", "title":"Niste Baieti - &quot;Sus in deal&quot; LIVE cover Pokefest Bucuresti 19.09.2009"},
{"file":"52cQeFBU2Kw", "provider":"youtube", "title":"The Who - Happy Jack"},
{"file":"zr3zb_fvGjs", "provider":"youtube", "title":"Royal Canoe - Bathtubs (Official Video)"},
{"file":"QBu_bzxvgdI", "provider":"youtube", "title":"MGMT - Alien Days"},
{"file":"Db4yB32hK8A", "provider":"youtube", "title":"Dylan Reynolds - Looking Up"},
{"file":"AKnqiknaYcY", "provider":"youtube", "title":"Clubfeet - Heartbreak"},
{"file":"jclHisjkJYI", "provider":"youtube", "title":"Pete Yorn - On Your Side"},
{"file":"yI7nEaCh2Lo", "provider":"youtube", "title":"The Acid - Tumbling Lights (Official Audio)"},
{"file":"nsufd9Ckiko", "provider":"youtube", "title":"Alexander Robotnick - Undicidisco (Justin VanDerVolgen Edit)"},
{"file":"WwIg4noNaE8", "provider":"youtube", "title":"Mack the knife - Ella Fitzgerald &amp; Duke Ellington"},
{"file":"q2bwKAPgsyA", "provider":"youtube", "title":"Anathema - The Lost Song part 3 (FULL TRACK) (from Distant Satellites)"},
{"file":"0zCMZf0g0Tg", "provider":"youtube", "title":"Cosmin Vaman - Nu sunt destul de trist sa fiu folkist (live Radio Romania Actualitati)"},
{"file":"zhxOiY_m7BI", "provider":"youtube", "title":"Zgarie Nori - Visul Tau "},
{"file":"u4XevlloPY4", "provider":"youtube", "title":"Steven Wilson - The Raven that Refused to Sing"},
{"file":"EvCoZplApPc", "provider":"youtube", "title":"Angel Haze - Wicked Moon Ft. Nicole Wray"},
{"file":"62eVwF2PvPo", "provider":"youtube", "title":"Popof - High &amp; Down"},
{"file":"14MNoifwXbY", "provider":"youtube", "title":"Seasick Steve - Down on the farm"},
{"file":"0XZLlZ9vbfI", "provider":"youtube", "title":"Asaf Avidan &amp; The Mojos - your anchor"},
{"file":"93x6nURAIFM", "provider":"youtube", "title":"Luka Sulic - Clair de Lune (Debussy)"},
{"file":"tS0mQ25ezq4", "provider":"youtube", "title":"Slayer - Disciple"},
{"file":"sA5hj7wuJLQ", "provider":"youtube", "title":"Bring Me The Horizon - &quot;Empire (Let Them Sing)&quot; (Full Album Stream)"},
{"file":"BgkYJskW3eo", "provider":"youtube", "title":"Arcade Fire - Porno"},
{"file":"kRUyRuouppw", "provider":"youtube", "title":"Two Shoes - The Cat Empire"},
{"file":"-dyO9SWiY7k", "provider":"youtube", "title":"Jim Carrey - Cuban Pete"},
{"file":"iY4APDrl66s", "provider":"youtube", "title":"Radiohead &quot;All I Need&quot;"},
{"file":"NSkTygQ7_qY", "provider":"youtube", "title":"Nude - Radiohead live from the basement"},
{"file":"dWABLspYtI8", "provider":"youtube", "title":"Radiohead - Nude (Strings Remix)"},
{"file":"1gwO_d8KY38", "provider":"youtube", "title":"I Am Kloot - Someone Like You"},
{"file":"sW2_VpKdUJY", "provider":"youtube", "title":"Yumi And The Weather - Not Again"},
{"file":"m_Y7So3tza8", "provider":"youtube", "title":"Tycho performing &quot;Awake&quot; Live on KCRW"},
{"file":"0Sq91sZE-yk", "provider":"youtube", "title":"Damon Albarn - The Selfish Giant"},
{"file":"9DvgLuXFrKY", "provider":"youtube", "title":"Sherlock Holmes Soundtrack - My Mind Rebels At Stagnation"},
{"file":"H-b9hgd-3Tc", "provider":"youtube", "title":"Modeselektor feat. Thom Yorke - The White Flash"},
{"file":"ZpbzBz6GfWE", "provider":"youtube", "title":"Thom Yorke - Skip Divided (Modeselektor Remix)"},
{"file":"k8XSV-qoHDQ", "provider":"youtube", "title":"Modeselektor feat. Thom Yorke &quot;Shipwreck&quot; "},
{"file":"afw5Z7XNDUQ", "provider":"youtube", "title":"Modeselektor feat. Thom Yorke - This"},
{"file":"ADYGXyAggFg", "provider":"youtube", "title":"Robin and the Backstabbers - Cand te-am cunoscut Cristina"},
{"file":"f2RBBHqoEi8", "provider":"youtube", "title":"Rose - C'est donc rien"},
{"file":"OjRXtZ2oZm4", "provider":"youtube", "title":"Niste baieti - Deschideti poarta soarelui"},
{"file":"4aeETEoNfOg", "provider":"youtube", "title":"Smashing Pumpkins 1979 video"},
{"file":"N1tTN-b5KHg", "provider":"youtube", "title":"Peter Gabriel - Sledgehammer "},
{"file":"CQgLa-840GM", "provider":"youtube", "title":"Lana Del Rey - West Coast (Camo &amp; Krooked Remix)"},
{"file":"RkpT948yTGw", "provider":"youtube", "title":"Garbage - Girls Talk feat. Brody Dalle (Official Video)"},
{"file":"NQm0O6vM8Y4", "provider":"youtube", "title":"Pomplamoose - La Vie En Rose (KGRL FPA Live Session) 1080p HD"},
{"file":"mlTPBCGPYLY", "provider":"youtube", "title":"Pink Floyd - Wearing The Inside Out"},
{"file":"UGtKGX8B9hU", "provider":"youtube", "title":"Oldelaf - Le cafe eng subbed"},
{"file":"Zkz6qKCYjDM", "provider":"youtube", "title":"Savages - &quot;Fuckers&quot;"},
{"file":"_BJ9AJ7iwIg", "provider":"youtube", "title":"Hans Zimmer - Time - (Instrumental Core Remix)"},
{"file":"XTb9GNIxpMk", "provider":"youtube", "title":"Pearl Jam - Just Breathe"},
{"file":"EC58867mfiA", "provider":"youtube", "title":"Radiohead - Codex [From the Basement HD] video reworked"},
{"file":"SBcADQziQWY", "provider":"youtube", "title":"Alice In Chains - Check My Brain"},
{"file":"2Hc5RuGrPow", "provider":"youtube", "title":"The Night That Never End - The Cat Empire"},
{"file":"plPyIBdD09E", "provider":"youtube", "title":"Blur - Death Of A Party"},
{"file":"QsgBtSCnUMU", "provider":"youtube", "title":"The Cat Empire - The Wine Song"},
{"file":"6yCIDkFI7ew", "provider":"youtube", "title":"The Black Keys - Gold On The Ceiling "},
{"file":"Wk1jqQi8eb0", "provider":"youtube", "title":"Ada Milea, Plai &amp; manea"},
{"file":"7oEGiTg_Xi8", "provider":"youtube", "title":"Callisto - Storm"},
{"file":"b7TPXBqaWU8", "provider":"youtube", "title":"Rishloo - Weevil Bride"},
{"file":"TBYOgS7USGk", "provider":"youtube", "title":"Rishloo - Feathergun In The Garden Of The Sun"},
{"file":"h38Qn--kfoU", "provider":"youtube", "title":"RISHLOO - Keyhole In The Sky"},
{"file":"pAWJvVJoVmg", "provider":"youtube", "title":"Phaeleh - Whistling in the Dark feat. Augustus Ghost"},
{"file":"3oLxt586JvU", "provider":"youtube", "title":"Feist - My Moon My Man (Grizzly Bear Remix)"},
{"file":"Op5hTbGnats", "provider":"youtube", "title":"Blur - Me, White Noise (Alternate Version)"},
{"file":"kS9SUmAyKWM", "provider":"youtube", "title":"Hungry Ghosts - I Don't Think About You Anymore But, I Don't Think About You Anyless"},
{"file":"BJHkudGBWj0", "provider":"youtube", "title":"Hungry Ghosts - Nothing Has To Happen"},
{"file":"VGvHnDeS12o", "provider":"youtube", "title":"Grouplove - Ways To Go"},
{"file":"M7VhSN26_WM", "provider":"youtube", "title":"Dan Croll - In / Out"},
{"file":"KYdB3rectmc", "provider":"youtube", "title":"Dan Croll - From Nowhere"},
{"file":"BB7R0ZY9w94", "provider":"youtube", "title":"Neon Trees - Sleeping With A Friend"},
{"file":"rWXF5FZN8DM", "provider":"youtube", "title":"Jamiroquai - Virtual Insanity - The Torres Project - Acoustic cover"},
{"file":"4JkIs37a2JE", "provider":"youtube", "title":"Jamiroquai - Virtual Insanity"},
{"file":"x0-EyHT1lJk", "provider":"youtube", "title":"Mastodon - High Road [Official Audio]"},
{"file":"TEAcQ-mhnmY", "provider":"youtube", "title":"&quot;Baba O'Riley&quot; (The Who Cover) - Live At Madison Square Garden - Pearl Jam"},
{"file":"Px7xb7qGIQQ", "provider":"youtube", "title":"Chet Faker - Cigarettes and Chocolate"},
{"file":"GZR2V0F5YSc", "provider":"youtube", "title":"Bill Laurance - Neverending City (Flint)"},
{"file":"SMrsSlpve6U", "provider":"youtube", "title":"Sea of Bees - Skinnybone"},
{"file":"gW2HX1pdIGc", "provider":"youtube", "title":"Hannah Peel: Tainted Love"},
{"file":"gx4rsZkCCss", "provider":"youtube", "title":"Seinabo Sey - Younger (Kygo Remix)"},
{"file":"79Oirr6Y0KA", "provider":"youtube", "title":"The Cure Acoustic Close To Me"},
{"file":"V2i2ag2yuCI", "provider":"youtube", "title":"Radiohead - Everything In Its Right Place [Pretty Lights remix]"},
{"file":"pbgZnowHiMU", "provider":"youtube", "title":"Antimatter - Expire"},
{"file":"uqx4o6QyywU", "provider":"youtube", "title":"Elbow - Weather To Fly"},
{"file":"Nj8r3qmOoZ8", "provider":"youtube", "title":"Arctic Monkeys - Arabella "},
{"file":"VUb450Alpps", "provider":"youtube", "title":"Temple of the Dog - Hunger Strike"},
{"file":"3zuEfmmCA5s", "provider":"youtube", "title":"Pink Floyd - Set the Controls for the Heart of the Sun"},
{"file":"__OSyznVDOY", "provider":"youtube", "title":"Charles Mingus - Moanin'"},
{"file":"n9_pIla12qA", "provider":"youtube", "title":"Tides From Nebula - Only With Presence (official video)"},
{"file":"EzCKrwOme2U", "provider":"youtube", "title":"Muse - Butterflies and Hurricanes "},
{"file":"x5gXnced4ls", "provider":"youtube", "title":"Flying Lotus - Puppet Talk"},
{"file":"YrzWh4cp4NA", "provider":"youtube", "title":"David Gilmour - Red Sky At Night.wmv"},
{"file":"VxHIVxz1K5M", "provider":"youtube", "title":"Rage Against The Machine - Maggie's Farm"},
{"file":"-2KBgXThyOo", "provider":"youtube", "title":"Faithless - Miss U Less, See U More"},
{"file":"SbC1uOjNh6A", "provider":"youtube", "title":"Junip - Without You "},
{"file":"MshHFy5fmJU", "provider":"youtube", "title":"Red Wing Special - Jimmy Herring"},
{"file":"KVtSCAJrZ50", "provider":"youtube", "title":"Damien Jurado - Best Dress"},
{"file":"Nbe5RERDh4k", "provider":"youtube", "title":"Nick Cave &amp; The Bad Seeds - Stagger Lee"},
{"file":"tBVUmakz_4M", "provider":"youtube", "title":"Litera 1 - Imaginar (HD official video)"},
{"file":"xLKycTJsJ0o", "provider":"youtube", "title":"Muse Clip - Muscle Museum (Soulwax Remix)"},
{"file":"ZhZCXnotGJ8", "provider":"youtube", "title":"Theory of Mind - Maggie"},
{"file":"ZsP-M9-xMQ0", "provider":"youtube", "title":"byron - The Alchemist (Live Underground in Salina Turda - DVD/Blu-ray)"},
{"file":"Zy5Uyo-gaEo", "provider":"youtube", "title":"The raconteurs - blue veins"},
{"file":"SkkIwO_X4i4", "provider":"youtube", "title":"Gogol Bordello - start wearing purple"},
{"file":"agIk2iaSCyU", "provider":"youtube", "title":"Ad Hoc - Nefiltrata"},
{"file":"cye3ke2b5lw", "provider":"youtube", "title":"Pasarea Colibri - Ce de lupi se inconjoara"},
{"file":"xI9PktYUN_8", "provider":"youtube", "title":"Green Fields - The Good, The Bad and The Queen (Audio Only)"},
{"file":"PC22Lcxumgk", "provider":"youtube", "title":"Radiohead - Reckoner (Scotch Mist Version)"},
{"file":"lTmRFbzPlCU", "provider":"youtube", "title":"Sequin - Naive"},
{"file":"XUiPpgFlUME", "provider":"youtube", "title":"The Soul Stirrers - Wade In The Water"},
{"file":"-pWm4TDrM8A", "provider":"youtube", "title":"All We Are - Feel Safe (Official Video)"},
{"file":"VOo9_EPkJ-o", "provider":"youtube", "title":"Blur - Ambulance"},
{"file":"KrPQtpCBJqw", "provider":"youtube", "title":"E.M.I.L. - Fara regrete"},
{"file":"jYeq6XoOg8s", "provider":"youtube", "title":"Dave Rawlings Machine - Going to California (Live at Georgia Theatre)"},
{"file":"C-yP9f0gadU", "provider":"youtube", "title":"Gorillaz - Empire Ants ft. Little Dragon"},
{"file":"TmEdJI8A76A", "provider":"youtube", "title":"MONO (Japan) - &quot;Dream Odyssey&quot; Official Video"},
{"file":"AoLogdbVS3U", "provider":"youtube", "title":"Nat King Cole - Those Lazy Crazy-Hazy-Days Of Summer"},
{"file":"XkNQ1FtQUTw", "provider":"youtube", "title":"Long distance calling - Time bends"},
{"file":"EreTmEZ4teg", "provider":"youtube", "title":"Dropkick Murphys - Deeds Not Words"},
{"file":"0n3OepDn5GU", "provider":"youtube", "title":"Roxy Music - Love Is The Drug"},
{"file":"6Aad3ITMumE", "provider":"youtube", "title":"Stoned Jesus -  I'm The Mountain (+ lyrics)"},
{"file":"qn9AeUK-jG4", "provider":"youtube", "title":"Keys N Krates - ALL THE TIME (TOVE LO FLIP)"},
{"file":"mZ_GgOysu6o", "provider":"youtube", "title":"Comfortably Numb - Pink Floyd music video"},
{"file":"tZtEtiJxQxM", "provider":"youtube", "title":"The Chemical Brothers - Hanna's theme (vocal version)"},
{"file":"UC2gxuvoiqA", "provider":"youtube", "title":"Tangled Thoughts of Leaving - Deep Rivers Run Quiet"},
{"file":"rqVMfTz_HDU", "provider":"youtube", "title":"Santa Claus is back in town - Elvis Presley"},
{"file":"yMMgZE513Ww", "provider":"youtube", "title":"Efterklang - Dreams Today"},
{"file":"tiwTF6waO9M", "provider":"youtube", "title":"Thy Veils - Adâncime (live)"},
{"file":"vFwYJYl5GUQ", "provider":"youtube", "title":"Type O Negative - Black No. 1 "},
{"file":"RfoqELZWcp8", "provider":"youtube", "title":"Jack Johnson - Better Together"},
{"file":"7aRzZGyBMro", "provider":"youtube", "title":"Blanoz ft. Luiza Zan - then we go on"},
{"file":"8IJzYAda1wA", "provider":"youtube", "title":"La vie en rose - Louis Armstrong"},
{"file":"NrgcRvBJYBE", "provider":"youtube", "title":"Noir Désir - Le Vent Nous Portera"},
{"file":"WZMMVIslGUQ", "provider":"youtube", "title":"Nava Mama - Ne asteapta (Live la Baia Turceasca)"},
{"file":"LeuxCvhUKhI", "provider":"youtube", "title":"Phoenix Pasarea roc   k and roll"},
{"file":"T1vDcRWGuqQ", "provider":"youtube", "title":"Kumm - Să nu spui nimănui "},
{"file":"tVUVANeJMF0", "provider":"youtube", "title":"Maps - I Heard Them Say"},
{"file":"OYsre4g7ZVg", "provider":"youtube", "title":"Vive la Fête - I Was Made For Loving You (KISS Cover)"},
{"file":"hLhN__oEHaw", "provider":"youtube", "title":"Iggy Pop - The Passenger"},
{"file":"jsjDWfj6DAQ", "provider":"youtube", "title":"Fredrika Stahl - Ghosts'N Beasts (Acoustic)"},
{"file":"nlql6M5nKo4", "provider":"youtube", "title":"Theory of Mind - Paradigm"},
{"file":"SYM-RJwSGQ8", "provider":"youtube", "title":"Tove Lo - Stay High (Habits Remix) ft. Hippie Sabotage"},
{"file":"foK3xPc61UM", "provider":"youtube", "title":"Arms and Sleepers - The Architekt (Lymbyc Systym remix)"},
{"file":"4jP9Q2QDZms", "provider":"youtube", "title":"David Bowie - You Feel So Lonely You Could Die [HD]"},
{"file":"tKONNhMvPtI", "provider":"youtube", "title":"Meniscus - 130 (Earth - Time Lapse View from Space, Fly Over - NASA, ISS)  High Definition"},
{"file":"1QO191imv0s", "provider":"youtube", "title":"Rise (Live) - Eddie Vedder - Water on the Road"},
{"file":"5up8kJoCsJM", "provider":"youtube", "title":"Kasabian - Underdog"},
{"file":"3KrbVkfzxcI", "provider":"youtube", "title":"Arms and Sleepers - Simone"},
{"file":"qUk4SI9utxw", "provider":"youtube", "title":"Queens of the Stone Age - Smooth Sailing"},
{"file":"teLxHc3VXWM", "provider":"youtube", "title":"Efterklang - Told To Be Fine"},
{"file":"C9OfBcjyxKY", "provider":"youtube", "title":"Queens of the Stone Age - I Appear Missing"},
{"file":"HgAcDLZr6Gs", "provider":"youtube", "title":"Muddy Waters - Hoochie Coochie Man - JazzAndBluesExperience"},
{"file":"RXlRhkegkM0", "provider":"youtube", "title":"Pixies - Where Is My Mind (Bassnectar Remix)"},
{"file":"wCV2mSj3t3w", "provider":"youtube", "title":"Robin and the Backstabbers - Vanatoarea Regala"},
{"file":"38vBSlpwKJY", "provider":"youtube", "title":"The Horrors - So Now You Know"},
{"file":"4V0N1x675FQ", "provider":"youtube", "title":"BARONESS - &quot;Take My Bones Away&quot;"},
{"file":"_Zko7pBeHkk", "provider":"youtube", "title":"Fu Manchu - King Of The Road"},
{"file":"ZQgYn23Xvck", "provider":"youtube", "title":"Dazed And Confused-Led Zeppelin"},
{"file":"RuLCPYLHR9o", "provider":"youtube", "title":"Sleep Party People - I'm Not Human At All"},
{"file":"gQ99OMlI5cg", "provider":"youtube", "title":"Snarky Puppy - Binky "},
{"file":"cKR6InhHlWg", "provider":"youtube", "title":"Them Crooked Vultures - Mind Eraser, No Chaser "},
{"file":"hii17sjSwfA", "provider":"youtube", "title":"Tool - Vicarious"},
{"file":"o26eIy1oM9A", "provider":"youtube", "title":"Tycho - Dye"},
{"file":"SDsxkQk6DWw", "provider":"youtube", "title":"The Greatest Cat Power"},
{"file":"8A604BZ1YZU", "provider":"youtube", "title":"Thom Yorke - And It Rained All Night"},
{"file":"w47RNPRe3co", "provider":"youtube", "title":"Arctic Monkeys - Old Yellow Bricks"},
{"file":"4Qo1NFwMhBA", "provider":"youtube", "title":"Snarky Puppy - Outlier (We Like It Here)"},
{"file":"df76hEIrh1k", "provider":"youtube", "title":"God Is An Astronaut - Sunrise In Aries"},
{"file":"9Ymsbsw8aII", "provider":"youtube", "title":"Troll Bends Fir  - &quot;Ave Celia!&quot; Screaming Banshee/Histomedia"},
{"file":"xHYmbQGBdEs", "provider":"youtube", "title":"Deftones - Risk"},
{"file":"wg5geyUlU4Y", "provider":"youtube", "title":"The National - &quot;Conversation 16&quot; "},
{"file":"jhat-xUQ6dw", "provider":"youtube", "title":"Queensryche - Silent Lucidity"},
{"file":"LqIEkY6r6vU", "provider":"youtube", "title":"Floex - Forget-Me-Not"},
{"file":"kS2w5B0MvvY", "provider":"youtube", "title":"Bon Iver - Skinny Love (Das Kapital Rerub) [HQ]"},
{"file":"a838F0EV-8Q", "provider":"youtube", "title":"Kasabian - Acid Turkish Bath (Shelter from the Storm)"},
{"file":"11GYvfYjyV0", "provider":"youtube", "title":"Red Hot Chili Peppers - Road Trippin' "},
{"file":"JRwijpJqLUw", "provider":"youtube", "title":"Hammock - Cold Front"},
{"file":"6mKtt7F0rPU", "provider":"youtube", "title":"One Day As A Lion - &quot;Wild International&quot;"},
{"file":"K3cG09lifTg", "provider":"youtube", "title":"Angelo Badalamenti - Dub Driving (Lost Highway)"},
{"file":"3FhFnGBZRpc", "provider":"youtube", "title":"fLako - Lonely Town (feat. Dirg Gerner)"},
{"file":"a_CiZxx3yWc", "provider":"youtube", "title":"teardrop - on acoustic bass"},
{"file":"CjP2BQA5HRI", "provider":"youtube", "title":"White Blank Page "},
{"file":"D67kmFzSh_o", "provider":"youtube", "title":"David Bowie- Space Oddity Original Video "},
{"file":"iWza_On7ajs", "provider":"youtube", "title":"Mumford &amp; Sons - Babel"},
{"file":"EF_xdvn52As", "provider":"youtube", "title":"Muse - The 2nd Law: Unsustainable"},
{"file":"Oc6zXSdYXm8", "provider":"youtube", "title":"Sigur Rós - Brennisteinn"},
{"file":"4BJDNw7o6so", "provider":"youtube", "title":"Phoenix -&quot;Mica tiganiada&quot;"},
{"file":"Z0x6cxLoPmg", "provider":"youtube", "title":"Modern Drift by Efterklang - official video"},
{"file":"UU9NkGultdM", "provider":"youtube", "title":"Cuibul - Space Wife (acoustic session)"},
{"file":"C5a1Cl_JOJM#t=27", "provider":"youtube", "title":"The Black Keys - Turn Blue [Official Audio]"},
{"file":"w3QW8PVyyNM", "provider":"youtube", "title":"Sigur Rós - The Rains of Castamere (Game of Thrones Season 4)"},
{"file":"rWn9LrZRyEA", "provider":"youtube", "title":"God Is An Astronaut - Red Moon Lagoon"},
{"file":"SDigfY_yOIw", "provider":"youtube", "title":"Nava Mama - Svet (Live la Baia Turceasca)"},
{"file":"8zz5o3TLzlM", "provider":"youtube", "title":"Pional - In Another Room"},
{"file":"FuIB8HEmnoY", "provider":"youtube", "title":"Savages - &quot;Shut Up&quot;"},
{"file":"MzQ5o7b7qf0", "provider":"youtube", "title":"Mastodon - Oblivion "},
{"file":"_XvWcYTj6dc", "provider":"youtube", "title":"Violent Soho - Saramona Said (Official Video)"},
{"file":"vTe7zcX6HL4", "provider":"youtube", "title":"No Surprises (Radiohead by Jacques Stotzem)"},
{"file":"GA5FcJyMYQI", "provider":"youtube", "title":"Lake of Tears - Headstones"},
{"file":"4b1wt3-zpzQ", "provider":"youtube", "title":"George Baker- Little Green Bag"},
{"file":"sIxSmg14UOA", "provider":"youtube", "title":"Placebo - Drag (Redux Version)"},
{"file":"NR6j7yLltfw", "provider":"youtube", "title":"And So I Watch You From Afar - Gangs - 1/ BEAUTIFULUNIVERSEMASTERCHAMPION"},
{"file":"QDvt5q6bt1s", "provider":"youtube", "title":"Game of Thrones Theme - The &quot;Smooth&quot; Version ft. Dave Koz"},
{"file":"pLgJ7pk0X-s", "provider":"youtube", "title":"The Ukulele Orchestra of Great Britain - The Good, The Bad and The Ugly"},
{"file":"d-FKM3eZTO8", "provider":"youtube", "title":"The Dillinger Escape Plan - ONE OF US IS THE KILLER (Official Music Video)"},
{"file":"TD5X9NSJrHE", "provider":"youtube", "title":"Dope D.O.D. - Psychosis (Featuring Sean Price)"},
{"file":"HSce0GvHLhk", "provider":"youtube", "title":"Radiohead - Nude (Silent Rider Remix)"},
{"file":"I0J7wOAR0rI", "provider":"youtube", "title":"Pelican perform Immutable Dusk (Live on Sound Opinions)"},
{"file":"A2Xo1woBq50", "provider":"youtube", "title":"Massive Attack - Angel (the Dillinger Escape Plan remix)"},
{"file":"E2Xe41WLT5g", "provider":"youtube", "title":"1000mods - vidage"},
{"file":"Z9IODJdi3GA", "provider":"youtube", "title":"Radiohead - All I Need [live From the Basement]"},
{"file":"9wSn81dLK6s", "provider":"youtube", "title":"Fine Young Cannibals - She Drives Me Crazy"},
{"file":"ig7UIKG4zDc", "provider":"youtube", "title":"ON AN ON - Ghosts"},
{"file":"KXFprnuyOEM", "provider":"youtube", "title":"God Is An Astonaut - Echoes"},
{"file":"msDsL3Y7xfQ", "provider":"youtube", "title":"Wicked Moon - Angel Haze ft. Nicole Wray"},
{"file":"VufilzHKTqk", "provider":"youtube", "title":"RED FANG - &quot;Prehistoric Dog&quot; (Official Music Video)"},
{"file":"JUj21OLAGvw", "provider":"youtube", "title":"BYRON - Gett Off, Live in Cafeneaua Artistilor, Buzau, 29.03.2014"},
{"file":"px4uQ8HIpbM", "provider":"youtube", "title":"Kumm - Vorbe-n vant"},
{"file":"wDt0pzhw4GM", "provider":"youtube", "title":"COMA - un semn .mp4"},
{"file":"YiOic5K4fEc", "provider":"youtube", "title":"Unwritten Law - Elva"},
{"file":"od_CDrF3fss", "provider":"youtube", "title":"God Is An Astronaut - Spiral Code"},
{"file":"M57Fi19vcSI", "provider":"youtube", "title":"André Rieu - And The Waltz Goes On "},
{"file":"uJ_1HMAGb4k", "provider":"youtube", "title":"Vance Joy - 'Riptide' Official Video"},
{"file":"ma9I9VBKPiw", "provider":"youtube", "title":"Arctic Monkeys - 'Fluorescent Adolescent' "},
{"file":"jI6OupafUgY", "provider":"youtube", "title":"Crippled Black Phoenix   Rise Up And Fight"},
{"file":"luM6oeCM7Yw", "provider":"youtube", "title":"Mogwai - Take Me Somewhere Nice"},
{"file":"HoRkntoHkIE", "provider":"youtube", "title":"Phillip Phillips - Home"},
{"file":"2yZBE5qLw8Y", "provider":"youtube", "title":"Radiohead - House Of Cards (Scotch Mist Version)"},
{"file":"9eWewdTkghM", "provider":"youtube", "title":"Ólafur Arnalds - Only The Winds"},
{"file":"d7Bg3nbzJd8", "provider":"youtube", "title":"Lights Out! - Downcast (feat. Nuages Quartet)"},
{"file":"F4IwxzU3Kv8", "provider":"youtube", "title":"Yat-Kha - Kaa-Khem"},
{"file":"6yuJFf3WdQg", "provider":"youtube", "title":"Dracula Blues - Alexandru Andries"},
{"file":"JzZ-Mgi1My4", "provider":"youtube", "title":"The Cure - To Wish Impossible Things"},
{"file":"60JqKDcrh5k", "provider":"youtube", "title":"Thriftworks - Trotter | HD"},
{"file":"uShqlufsq5w", "provider":"youtube", "title":"MASTODON - &quot;March of the Fire Ants&quot;"},
{"file":"4W0B-1iF6S4", "provider":"youtube", "title":"Can't Keep - Eddie Vedder"},
{"file":"p6CEuIQPgAc", "provider":"youtube", "title":"Ada Milea - Ala "},
{"file":"n0F-8ZF1eug", "provider":"youtube", "title":"Bon Iver - Minnesota, WI (Oliver Nelson Remix)"},
{"file":"BopLWdixRkM", "provider":"youtube", "title":"Radiohead - I Might Be Wrong"},
{"file":"PTFwQP86BRs", "provider":"youtube", "title":"Nine Inch Nails - Closer "},
{"file":"JRWox-i6aAk", "provider":"youtube", "title":"Lana Del Rey - Blue Jeans"},
{"file":"HX6ndnb80h0", "provider":"youtube", "title":"The Kills - No Wow "},
{"file":"veRWEt-VtPk", "provider":"youtube", "title":"Christoph Pepe Auer &amp; Manu Delago - Libertango (Life in Rooms 1/7)"},
{"file":"4EWiY9xXrug", "provider":"youtube", "title":"Warpaint - Burgundy"},
{"file":"-VgnjGfk-P0", "provider":"youtube", "title":"Portishead feat Moloko - Fun for me - Remixes"},
{"file":"AGOsZP0HoVs", "provider":"youtube", "title":"Portico Quartet - Pompidou Pt.2"},
{"file":"HpO_F_F-Rcs", "provider":"youtube", "title":"Damon Albarn - Heavy Seas Of Love (Official Audio)"},
{"file":"RN9NC4iQcsA", "provider":"youtube", "title":"Violent Soho - Covered in Chrome (Official Video)"},
{"file":"16ptWIZ36F4", "provider":"youtube", "title":"(Crosses) - The Epilogue (Official Music Video)"},
{"file":"aYJ8_93krG4", "provider":"youtube", "title":"Where is my mind - Maxence Cyrin"},
{"file":"Cmpv0lWEdR0", "provider":"youtube", "title":"Sonny Terry &amp; Brownie McGhee - Hole In The Wall"},
{"file":"SNx_Nyxf-4o", "provider":"youtube", "title":"M83 - Don't Save Us From The Flames"},
{"file":"t_OHvffAOmA", "provider":"youtube", "title":"Bring Me The Horizon - Shadow Moses "},
{"file":"gNi2oxH37vo", "provider":"youtube", "title":"Star Wars | &quot;Cantina Band&quot; | Ragtime Piano Duet | Martin Spitznagel &amp; Bryan Wright"},
{"file":"1ICJUFOJa2g", "provider":"youtube", "title":"Joshua Redman - Jazz Crimes "},
{"file":"RqM9vFcQE0M#t=215", "provider":"youtube", "title":"Meniscus - DBT (Official Music Video)"},
{"file":"sDXxX2IhT98", "provider":"youtube", "title":"TOO MUCH RAIN Paul McCartney"},
{"file":"GQ3w2s3UxO4", "provider":"youtube", "title":"Deftones - Swerve City"},
{"file":"yoxRxGHYTsg", "provider":"youtube", "title":"One Hour Before The Trip ~ Vagabond"},
{"file":"mtOxVbsuc00", "provider":"youtube", "title":"Baroness-Back Where I Belong"},
{"file":"_6khld0NiME", "provider":"youtube", "title":"Metallica - The God That Failed "},
{"file":"IYrbmx9c45c", "provider":"youtube", "title":"David Bowie Cover &quot;As the World Falls Down&quot;  by Luiza Zan and Matt Grundy"},
{"file":"KaWYjohc0aw", "provider":"youtube", "title":"Maybeshewill - To The Skies From A Hillside "},
{"file":"g3S3zuHRqlk", "provider":"youtube", "title":"Isis - So Did We"},
{"file":"-r9Hv5uYjOQ", "provider":"youtube", "title":"EMIL - Da Vrei"},
{"file":"dh3bleXWaCk", "provider":"youtube", "title":"Funkadelic - Maggot Brain"},
{"file":"Bg6ujjn-1Xg", "provider":"youtube", "title":"Vita De Vie - Incep Sa Pierd "},
{"file":"AVs84uFoWAI", "provider":"youtube", "title":"Atoms For Peace 6.3"},
{"file":"aF90hv6jKRs", "provider":"youtube", "title":"Get Well Soon - The Last Days Of Rome"},
{"file":"ADP65wbBUpc", "provider":"youtube", "title":"Ben Howard - Keep Your Head Up"},
{"file":"8L_tniTVYEQ", "provider":"youtube", "title":"Antimatter - Dream"},
{"file":"UaSMROk-D-A", "provider":"youtube", "title":"The Beatles - Blackbird"},
{"file":"3dZUDvIXeXI", "provider":"youtube", "title":"Hugh Laurie - Evenin'"},
{"file":"21wM3pbcHfM", "provider":"youtube", "title":"Radiohead - 15 Step Cover / Interpretation"},
{"file":"asePpcjl8Gs", "provider":"youtube", "title":"Crippled Black Phoenix - Northern Comfort - Official Video"},
{"file":"CFjMeOnqAPI", "provider":"youtube", "title":"Gary Clark Jr. - Bright Lights "},
{"file":"iWOyfLBYtuU", "provider":"youtube", "title":"Florence + The Machine - Dog Days Are Over (2010 Version)"},
{"file":"275UZJ1gsjU", "provider":"youtube", "title":"Karen O (From the Yeah Yeah Yeahs) - &quot;The Moon Song&quot; (From the Movie &quot;Her&quot;, by Spike Jonze)"},
{"file":"p9MMJgFKv24", "provider":"youtube", "title":"Damon Albarn - Lonely Press Play (Official Video)"},
{"file":"zr4OSu6WTRU", "provider":"youtube", "title":"Thelonious Monk - Easy Street"},
{"file":"gXN9acC9edU", "provider":"youtube", "title":"Muse- Stockholm Syndrome"},
{"file":"TqQIFgbpfXY", "provider":"youtube", "title":"Get Well Soon - Born Slippy Nuxx"},
{"file":"YS9gQeOzQMk", "provider":"youtube", "title":"I`m going upstairs - John Lee Hooker"},
{"file":"eFUOZ5PI3m8", "provider":"youtube", "title":"Snarky Puppy - Kite (We Like It Here)"},
{"file":"0wAMr3V5lN4", "provider":"youtube", "title":"Professor Longhair - Go To The Mardi Gras"},
{"file":"CvQROqvZgnk", "provider":"youtube", "title":"Placebo - Scene of the Crime"},
{"file":"uhrZiaH2QRk", "provider":"youtube", "title":"Theory of Mind - I Felt The Sun"},
{"file":"bShrtYXFQiY", "provider":"youtube", "title":"Radiohead - Climbing Up The Walls "},
{"file":"iNcygbTNJyE", "provider":"youtube", "title":"Billy Bragg - To Have And To Have Not"},
{"file":"4PAc5mgymbc", "provider":"youtube", "title":"parazitii - slalom printre cretini"},
{"file":"r8bCB7DHJts", "provider":"youtube", "title":"dan le sac vs scroobius pip - Waiting for the beat to kick in."},
{"file":"ddyaXnSN-Tg", "provider":"youtube", "title":"Timpuri noi - 1996 - Stere"},
{"file":"XQud7EFQ3zQ", "provider":"youtube", "title":"Nick Cave &amp; The Bad Seeds - Higgs Boson Blues "},
{"file":"G464EWjoahM", "provider":"youtube", "title":"&quot;Pinky and the Brain&quot; - The PROJECT Trio: Greg Pattillo, Eric Stephenson, Peter Seymour"},
{"file":"9QU_HigwsrY", "provider":"youtube", "title":"Lights Out! - Braille"},
{"file":"d8ROfaNB8_8", "provider":"youtube", "title":"New Born Cover"},
{"file":"tHCxKy2xWHs", "provider":"youtube", "title":"Crippled Black Phoenix - 01 Troublemaker (HQ)"},
{"file":"UOYZuaLg0J0", "provider":"youtube", "title":"The Tain"},
{"file":"ZtTMxBVFVSg", "provider":"youtube", "title":"Sting The Wild Wild Sea"},
{"file":"YlSwK5Lj2dc", "provider":"youtube", "title":"Jack Straw (acoustic Grateful Dead cover) - Mike Masse and Jeff Hall"},
{"file":"SpwSxHiiNSw", "provider":"youtube", "title":"Alela Diane - The Pirate's Gospel"},
{"file":"UoaS3JoNn38", "provider":"youtube", "title":"Pink Floyd - Mudmen"},
{"file":"BpTrHMKfGro", "provider":"youtube", "title":"Alternativ Quartet -07- Drumul catre tot ce-a fost mai rau pe lume se deschide decat joi"},
{"file":"-I_T3XvzPaM", "provider":"youtube", "title":"Paul Simon - Diamonds on the Soles of Her Shoes"},
{"file":"kg8oWjFoETY", "provider":"youtube", "title":"The Telescopes - Tesla Death Ray"},
{"file":"iKTF0o6wYhg", "provider":"youtube", "title":"Iannis Xenakis | Rebonds B"},
{"file":"NjzKkyQoe1U", "provider":"youtube", "title":"Thao with The Get Down Stay Down - When We Swam"},
{"file":"CWXJ4q-HMUE", "provider":"youtube", "title":"The Legend of Zelda, gypsy rumba style"},
{"file":"h0RQnGhxZzg", "provider":"youtube", "title":"EDWARD SHARPE &amp; THE MAGNETIC ZEROS - 40 DAY DREAM LIVE @ THE REGENT"},
{"file":"P8znYPXhZFA", "provider":"youtube", "title":"The Kooks - Kids (MGMT Cover)"},
{"file":"PeFJlk8eOhQ", "provider":"youtube", "title":"Jack Johnson - You And Your Heart"},
{"file":"bD2OsPy73gU", "provider":"youtube", "title":"Opeth - Deliverance"},
{"file":"46dZzwNeyF8", "provider":"youtube", "title":"Nomad Soul - Murmuration"},
{"file":"77sF4HvvCWM", "provider":"youtube", "title":"Them Crooked Vultures @ BBC Radio 1 - Dead End Friends"},
{"file":"aRV44m2ns7Y", "provider":"youtube", "title":"11   Tosca Tango Orchestra   Ballade 4, Pt  2   Waking Life"},
{"file":"U9vHdp9rOwY", "provider":"youtube", "title":"MARCIAN PETRESCU &amp; Trenul De Noapte - MUZICA SI MUZICHIE (7) - octombrie 2009"},
{"file":"hC3zEIlGv8A", "provider":"youtube", "title":"KT Tunstall vs Radiohead - Silent Bell (mashup by Overdub)"},
{"file":"ZbLLGC3zfu0", "provider":"youtube", "title":"Pelican - Forecast for today"},
{"file":"lIZdKQZV_iU", "provider":"youtube", "title":"Bon Iver - Wash"},
{"file":"qlekfZ433Rk", "provider":"youtube", "title":"Skyrim - The Elder Scrolls - harp / harpe (Morrowind theme, Main theme)"},
{"file":"0X-PRpqj7N4", "provider":"youtube", "title":"VideoSong 4 - Radiohead/Chopin Mashup - Jack Conte"},
{"file":"5RyTamwrzQk", "provider":"youtube", "title":"The Decemberists - My Mother Was a Chinese Trapeze Artist"},
{"file":"8MtaMscUiQY", "provider":"youtube", "title":"Daft Punk - Inception Mashup"},
{"file":"http://soundcloud.com/porticoquartet/portico-quartet-line-sbtrkt", "provider":"youtube", "title":"Portico Quartet - Line (SBTRKT Remix)"},
{"file":"fuhHU_BZXSk", "provider":"youtube", "title":"Snarky Puppy - What About Me? (We Like It Here)"},
{"file":"9P4GsF1zdzM", "provider":"youtube", "title":"Animals As Leaders - Tooth and Claw"},
{"file":"sYJBcr1LDg4", "provider":"youtube", "title":"Daft Punk - TRON Legacy Soundtrack [Complete Edition] -  HD"},
{"file":"U6EM4KmeaMQ", "provider":"youtube", "title":"JK Soul - It's So Hard (Original Mix)"},
{"file":"Q2L-tABHwBg", "provider":"youtube", "title":"Tides From Nebula live @ The Shelter"},
{"file":"BhvcqwZdaqU", "provider":"youtube", "title":"Tool - Eon Blue Apocalypse"},
{"file":"HWcfmkslT48", "provider":"youtube", "title":"M.O.P. - How About Some Hardcore "},
{"file":"RzTymuzFZLE", "provider":"youtube", "title":"Karen O And The Kids - Worried Shoes Lyrics (HD) (Where The Wild Things Are)"},
{"file":"J6LM-5-oC-k", "provider":"youtube", "title":"Violent Soho - Dope Calypso (Official Video)"},
{"file":"NnYYBM7caMs", "provider":"youtube", "title":"Lamb - Trans Fatty Acid (Kruder &amp; Dorfmeister)"},
{"file":"fyXmp-FiPJo", "provider":"youtube", "title":"Lisa Hannigan - Lille - OFFICIAL VIDEO"},
{"file":"2emGPh-PR-M", "provider":"youtube", "title":"The Ink Spots - Don't Get Around Much Anymore"},
{"file":"k5LxW0apRMg", "provider":"youtube", "title":"absurdcus - funkadelity  ( feat. my oldschool Jolana Alexis Super 2 bass )"},
{"file":"H5JpdqBKe_U", "provider":"youtube", "title":"The Kills - Venus In Furs (Velvet Underground cover)"},
{"file":"4KEEXyRL0qE", "provider":"youtube", "title":"Placebo - Running Up That Hill"},
{"file":"9j53D4o0CfQ", "provider":"youtube", "title":"The Cure - The drowning man"},
{"file":"1GKDo1dHeUQ", "provider":"youtube", "title":"Dave Brubeck - Take Five - 1966"},
{"file":"fqJ-xGl4Dbw", "provider":"youtube", "title":"Chorus Grant - O Everyone"},
{"file":"PhFl3Mr66Dk", "provider":"youtube", "title":"Pure X - Thousand Year Old Child"},
{"file":"3Kqw1NK0m-0", "provider":"youtube", "title":"Mugur de fluier - Phoenix"},
{"file":"C_fo-5BFSmQ", "provider":"youtube", "title":"Jazz Night Out - Snarky Puppy live in Silver Church- Bucharest 2013"},
{"file":"BrZTNhW44-o", "provider":"youtube", "title":"radiohead street spirit"},
{"file":"oWYp1xRPH5g", "provider":"youtube", "title":"Ed Sheeran - I See Fire (Kygo Remix)"},
{"file":"8KaNdiChAdI", "provider":"youtube", "title":"Fleet Foxes - Lorelai"},
{"file":"822P87a773c", "provider":"youtube", "title":"M83 - Oblivion "},
{"file":"g8PrTzLaLHc", "provider":"youtube", "title":"Imagine Dragons - On Top of the World - Lyrics"},
{"file":"PcaH2atNyVk", "provider":"youtube", "title":"Johann Sebastian Bach - Brandenburg Concerto No.3 in G major - 1st Movement"},
{"file":"SAHfs_Pb9HM", "provider":"youtube", "title":"Merry Christmas 2013"},
{"file":"tFTLxkMmY4M", "provider":"youtube", "title":"Radiohead - Staircase "},
{"file":"8gZygCUM61w", "provider":"youtube", "title":"Fink - Sort Of Revolution (The Cinematic Orchestra Remix)"},
{"file":"WUMo0a1g5gQ", "provider":"youtube", "title":"Heroin and your Veins-Bad Luck"},
{"file":"http://soundcloud.com/noisia/deadmau5-raise-your-weapon", "provider":"youtube", "title":"Deadmau5 - Raise Your Weapon (Noisia Remix)"},
{"file":"elfuaxHQWlQ", "provider":"youtube", "title":"Red Fang - Blood Like Cream (Official Music Video)"},
{"file":"GFqn1cg935A", "provider":"youtube", "title":"Neurotica - Country of nobody"},
{"file":"nQF0hs9Rzus", "provider":"youtube", "title":"Eels-Mr. E´s Beautiful Blues"},
{"file":"DYhcSNFo6RY", "provider":"youtube", "title":"Celelalte Cuvinte - www (Videoclip oficial)"},
{"file":"nnjoXKmO16I", "provider":"youtube", "title":"Mastodon - Sleeping Giant "},
{"file":"GWq3ifohM3A", "provider":"youtube", "title":"Enter Shikari - Constellations"},
{"file":"mGL1ysoUsT4", "provider":"youtube", "title":"Radiohead - Nude (City Rain Remix)"},
{"file":"KiglLBLkzeg", "provider":"youtube", "title":"WLT - Ben Howard - Old Pine"},
{"file":"DZPnq0burNE", "provider":"youtube", "title":"Jazz Night Out- Vijay Iyer Trio &amp; Tigran Trio-Sala Radio- October 17- Bucharest"},
{"file":"rpj1OXT6o2E", "provider":"youtube", "title":"I Sat By The Ocean (Live on Letterman)"},
{"file":"X70VMrH3yBg", "provider":"youtube", "title":"John Lee Hooker - Boom Boom [HQ]"},
{"file":"5n9gqVdD114", "provider":"youtube", "title":"Ukulele Thursdays: Episode 28 Blue Roses Falling"},
{"file":"esV4cqlKpGE", "provider":"youtube", "title":"Dan Byron si Luiza Zan - Surrealistic Collage @Verona Acoustic Season"},
{"file":"bBhcB7aub-I", "provider":"youtube", "title":"Caspian - &quot;Hymn For The Greatest Generation&quot; (audio)"},
{"file":"_w1gZp6Vojw", "provider":"youtube", "title":"Run Rudolph Run- Lemmy Kilmister"},
{"file":"lLJf9qJHR3E", "provider":"youtube", "title":"Mumford and Sons - Little Lion Man"},
{"file":"qMRJmrLYVTw", "provider":"youtube", "title":"'J.S. Bach - Suite for Solo Cello no. 1 in G major - Prelude' by Denise Djokic"},
{"file":"dqLPb0_ygKk", "provider":"youtube", "title":"TESSERACT - Nocturne (NEW TRACK - FREE DOWNLOAD)"},
{"file":"uosSo6y7G6g", "provider":"youtube", "title":"Ihsahn - Called By The Fire"},
{"file":"vhoAiXFISgA", "provider":"youtube", "title":"Kings of Leon - Mi Amigo"},
{"file":"gXFRck4LZJY", "provider":"youtube", "title":"White Walls - Dream Chaser (Official HD audio album stream - &quot;Escape Artist&quot; out now!"},
{"file":"o_-QGNUYL5g", "provider":"youtube", "title":"Rage Against The Machine-Bullet in your head"},
{"file":"-8Pk_WA-Q_Q", "provider":"youtube", "title":"ANATHEMA-UNIVERSAL"},
{"file":"RqwzpolVTBk", "provider":"youtube", "title":"Tom Waits - All Stripped Down"},
{"file":"QpPblSkLYE4", "provider":"youtube", "title":"Emir Kusturica &amp; The No Smoking Orchestra - Pitbull Terrier"},
{"file":"NBqbuGgt0Us", "provider":"youtube", "title":"Led Zeppelin - How Many More Times (Studio Version - Best Quality)"},
{"file":"4nJ9kAvjcdk", "provider":"youtube", "title":"HOWLIN' WOLF [ 1 ] ~ Electric Psychedelic Blues ~ 1969"},
{"file":"8ojg4vEDGjs", "provider":"youtube", "title":"Revolution Harmony - We Are (Serj Tankian, Ihsahn, Devin Townsend) OFFICIAL MUSIC VIDEO"},
{"file":"zOxWW7sB9Bk", "provider":"youtube", "title":"Mark Knopfler &amp; Eric Clapton - Money for nothing "},
{"file":"JzzSdrUjjAw", "provider":"youtube", "title":"Tangled Thoughts of Leaving - …And Sever Us From the Present"},
{"file":"pEDlO-jRNZo", "provider":"youtube", "title":"The Dillinger Escape Plan - Sunshine the Werewolf"},
{"file":"Yl-pXpXxK00", "provider":"youtube", "title":"Radiohead - Electioneering"},
{"file":"rjbiUj-FD-o", "provider":"youtube", "title":"Damon Albarn - Everyday Robots "},
{"file":"QBN-1Q0_Fiw", "provider":"youtube", "title":"Crosses  - Bitches Brew "},
{"file":"qQXP6TDtW0w", "provider":"youtube", "title":"&quot;Sirens&quot;  - Pearl Jam"},
{"file":"QYEC4TZsy-Y", "provider":"youtube", "title":"Lou Reed - Perfect Day"},
{"file":"QzT9KbfBKMQ", "provider":"youtube", "title":"Editors-Lullaby (The Cure Cover)"},
{"file":"r4tW3mhp9io", "provider":"youtube", "title":"Atoms for Peace - Judge Jury and Executioner"},
{"file":"RDN4awrpPQQ", "provider":"youtube", "title":"Metallica - The Memory Remains "},
{"file":"RVvTg-DBrt8", "provider":"youtube", "title":"Fine it's Pink - Live Session at Baia Turceasca"},
{"file":"_oLzX0RPquk", "provider":"youtube", "title":"Foster The People - Pumped Up Kicks"},
{"file":"1rvtrroofIk", "provider":"youtube", "title":"The XX - Intro [Long Version]"},
{"file":"T5N-h3EJ_n8", "provider":"youtube", "title":"12. Kazi Ploae - Neti Sandu "},
{"file":"w0o8JCxjjpM", "provider":"youtube", "title":"Explosions in the sky - First breath after coma"},
{"file":"wycjnCCgUes", "provider":"youtube", "title":"Tame Impala - Feels Like We Only Go Backwards"},
{"file":"XH-vzQwcf4c", "provider":"youtube", "title":"Pixies - Another Toe In the Ocean"},
{"file":"XnxSLwLFfNY", "provider":"youtube", "title":"Ólafur Arnalds - Full Performance "},
{"file":"xytnwmteGVI", "provider":"youtube", "title":"The Ocean-Abyssopelagic I Boundless Vasts"},
{"file":"Xz_-cNL87lg", "provider":"youtube", "title":"Little Dragon - Turn Left"},
{"file":"YcnvM2Eg_Rc", "provider":"youtube", "title":"Nirvana - Come as You Are  Live"},
{"file":"yFTvbcNhEgc", "provider":"youtube", "title":"Angus and Julia Stone - Big Jet Plane "},
{"file":"YJfV2n1Wa7k", "provider":"youtube", "title":"Phoenix - Pavel Cneazul, leat 1479"},
{"file":"YU1bTFWOxYw", "provider":"youtube", "title":"Jon Hopkins - Nightfall/Love Theme"},
{"file":"yUaCxx5npko", "provider":"youtube", "title":"Mogwai - The sun smells too loud"},
{"file":"ywxXjOVeaBU", "provider":"youtube", "title":"Mircea Baniciu - Un zvon"},
{"file":"ZWrUEsVrdSU", "provider":"youtube", "title":"Atoms for Peace - Before Your Very Eyes..."},
{"file":"1VuDjJ9KIxM", "provider":"youtube", "title":"The Police - Invisible Sun"},
{"file":"J712_dwLL2g", "provider":"youtube", "title":"Oskar Schuster - Matilda (live)"},
{"file":"9cQloro92xA", "provider":"youtube", "title":"The Last Shadow Puppets - My Mistakes Were Made For You"},
{"file":"4tXFA6jTulk", "provider":"youtube", "title":"Bonobo - Ketto"},
{"file":"5aqKA_2UUy4", "provider":"youtube", "title":"James Blake &amp; Bon Iver - Fall Creek Boys Choir"},
{"file":"4pEMd1SdkAE", "provider":"youtube", "title":"The Doors - Roadhouse Blues"},
{"file":"74hFIWjwDa4", "provider":"youtube", "title":"Balanescu Quartet - Waltz"},
{"file":"9pkLDEEs20U", "provider":"youtube", "title":"Rammstein - Ohne Dich"},
{"file":"9zdNdjF-htY", "provider":"youtube", "title":"The Arcade Fire - Wake Up"},
{"file":"A9QaOATItFE", "provider":"youtube", "title":"Tides from Nebula - These Days, Glory Days"},
{"file":"BKiNPgKCEBY", "provider":"youtube", "title":"Partizan IOR"},
{"file":"bpOSxM0rNPM", "provider":"youtube", "title":"Arctic Monkeys - Do I Wanna Know? "},
{"file":"cNrr9YUGjQk", "provider":"youtube", "title":"Kylesa - Set The Controls For The Heart Of The Sun"},
{"file":"mKDSpW8mXro", "provider":"youtube", "title":"Emir Kusturica &amp; The No Smoking Orchestra - Unza Unza Time"},
{"file":"dUa5yJNaLBs", "provider":"youtube", "title":"System Of A Down - Toxicity- Official Video"},
{"file":"EZl6BRY9IYQ", "provider":"youtube", "title":"Thom Yorke - Ingenue "},
{"file":"f0pdwd0miqs", "provider":"youtube", "title":"Deftones - Sextape "},
{"file":"FqCzP0HQpQo", "provider":"youtube", "title":"Florence And The Machine - Girl With One Eye"},
{"file":"Gy8GZ3qbkSI", "provider":"youtube", "title":"Tides From Nebula - Siberia"},
{"file":"i5eIhaQ-yus", "provider":"youtube", "title":"Dan Byron si Luiza Zan - Lotus Flower @Verona Acoustic Season"},
{"file":"Iuft0Sjza9w", "provider":"youtube", "title":"Luna Amara - Oameni Noi "},
{"file":"jNwXFnqBzHg", "provider":"youtube", "title":"The Wall - Roger Waters - Mother+Goodbye blue sky live Berlin 1990"},
{"file":"jQH0GPL33uc", "provider":"youtube", "title":"Portico Quartet - Ruins"},
{"file":"JSUIQgEVDM4", "provider":"youtube", "title":"The Doors - The End "},
{"file":"KbwIFzxD1-w", "provider":"youtube", "title":"Mogwai - The Lord Is Out of Control"},
{"file":"KwIe_sjKeAY", "provider":"youtube", "title":"Madness - Our House"},
{"file":"L0bcRCCg01I", "provider":"youtube", "title":"Gustav Holst - The Planets - Mars, the Bringer of War"},
{"file":"mLa0-sQg1YM", "provider":"youtube", "title":"Deftones - Minerva "},
{"file":"mpaPBCBjSVc", "provider":"youtube", "title":"The Black Keys - Tighten Up "},
{"file":"MqoANESQ4cQ", "provider":"youtube", "title":"The Cinematic Orchestra Arrival of the Birds &amp; Transformation"},
{"file":"mYIfiQlfaas", "provider":"youtube", "title":"Olafur Arnalds - Ljosio "},
{"file":"N8bSxWjJviQ", "provider":"youtube", "title":"Agent Fresco - A Long Time Listening "},
{"file":"NbQ0Cb6h3Ew", "provider":"youtube", "title":"Led Zeppelin bron-y-aur-stomp album version"},
{"file":"ouANEo2w0Pg", "provider":"youtube", "title":"★ Eddie Vedder - Society Into the Wild  HD"},
{"file":"PfAWReBmxEs", "provider":"youtube", "title":"Deep Purple-Child in Time"},
{"file":"pp-wmEKWLSo", "provider":"youtube", "title":"je ne veux pas travailler!"},
{"file":"2cr4YixJfi8", "provider":"youtube", "title":"06 - Anathema - The Storm Before The Calm"},
{"file":"8gjI67KBbRg", "provider":"youtube", "title":"Genesis - The Brazilian"},
{"file":"8LeQN249Jqw", "provider":"youtube", "title":"Sigur Ros - Olsen Olsen - HD"},
{"file":"8mlEYysM2T8", "provider":"youtube", "title":"Alexandru Andries - Mie mi-e somn"},
{"file":"9B-h1EEsKDA", "provider":"youtube", "title":"José González - 'Teardrop'"},
{"file":"9yAxIdkF2Qo", "provider":"youtube", "title":"Fleet Foxes - The Shrine / An Argument "},
{"file":"rAMtbQwkfog", "provider":"youtube", "title":"Rainy Day, Dream Away  - Jimi Hendrix"},
{"file":"aAXRKPGKXWs", "provider":"youtube", "title":"Radiohead - The Tourist"},
{"file":"BuSG3OV9Gnc", "provider":"youtube", "title":"OCS - In Zbor"},
{"file":"cUvEZgQC-tY", "provider":"youtube", "title":"Arms and Sleepers - The Architekt"},
{"file":"d8pihw0VMO8", "provider":"youtube", "title":"Kumm - Morsa"},
{"file":"WUOtCLOXgm8", "provider":"youtube", "title":"Queen - I Want To Break Free. ( official video )"},
{"file":"tzSiL5MsPAQ", "provider":"youtube", "title":"Massive Attack - Superpredators"},
{"file":"hlab0XVQkn0", "provider":"youtube", "title":"Mastodon - Pendulous Skin"},
{"file":"j9J5Zt2Obko", "provider":"youtube", "title":"Gene Krupa- Sing, Sing, Sing"},
{"file":"jdYJf_ybyVo", "provider":"youtube", "title":"OCEAN - John Butler - 2012 Studio Version"},
{"file":"3DuCIGvsbMA", "provider":"youtube", "title":"Ultravox - Vienna "},
{"file":"MejbOFk7H6c", "provider":"youtube", "title":"OK Go - Needing/Getting - Official Video"},
{"file":"MYWdRpM6Tp8", "provider":"youtube", "title":"The Dead Weather - Hang You From The Heavens"},
{"file":"cU7KoVI1gGY", "provider":"youtube", "title":"The Black Keys - Nova Baby"},
{"file":"To3W4U6IQfA", "provider":"youtube", "title":"The Silk Road Ensemble: Ascending Bird"},
{"file":"TWcyIpul8OE", "provider":"youtube", "title":"Bon Iver - Holocene "},
{"file":"YkADj0TPrJA", "provider":"youtube", "title":"Phil Collins - In The Air Tonight "},
{"file":"ZtLuDz3qCTc", "provider":"youtube", "title":"Arctic Monkeys - Dance Little Liar (humbug version)"},
{"file":"Z_hOR50u7ek", "provider":"youtube", "title":"Prokofiev: Romeo and Juliet, No 13 Dance of the Knights "}]